plugins {
    id("awesome-android-lib")
}

dependencies {
    implementation(projects.impl.weatherCheckout)
    implementation(projects.impl.identityCheckout)
    implementation(projects.impl.analyticsCart)
    implementation(projects.impl.galleryIdentity)
    implementation(projects.impl.playlistCheckout)
    implementation(projects.impl.audioCart)
    implementation(projects.impl.commentCart)
    implementation(projects.impl.loginCart)
    implementation(projects.impl.mapCheckout)
    implementation(projects.impl.locationCheckout)
    implementation(projects.impl.postCart)
    implementation(projects.impl.eventCheckout)
    implementation(projects.impl.documentCheckout)
    implementation(projects.impl.networkUser)
    implementation(projects.impl.mediaCart)
    implementation(projects.impl.articleCart)
    implementation(projects.impl.listCheckout)
    implementation(projects.impl.videoCheckout)
    implementation(projects.impl.newsCart)
    implementation(projects.impl.settingCheckout)
    implementation(projects.impl.identityUser)
    implementation(projects.impl.todoCheckout)
    implementation(projects.impl.checkoutUser)
    implementation(projects.impl.playlistIdentity)
    implementation(projects.impl.forecastCheckout)
    implementation(projects.impl.fileCart)
    implementation(projects.impl.articleCheckout)
    implementation(projects.impl.timerCheckout)
    implementation(projects.impl.searchCart)
    implementation(projects.impl.calendarCheckout)
    implementation(projects.impl.cartCheckout)
    implementation(projects.impl.postUser)
    implementation(projects.impl.fileCheckout)
    implementation(projects.impl.todoCart)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}