plugins {
    id("awesome-android-lib")
}

dependencies {
    implementation(projects.impl.identityCart)
    implementation(projects.impl.photoIdentity)
    implementation(projects.impl.audioCheckout)
    implementation(projects.impl.listCart)
    implementation(projects.impl.loginUser)
    implementation(projects.impl.analyticsCart)
    implementation(projects.impl.profileCart)
    implementation(projects.impl.audioIdentity)
    implementation(projects.impl.userCart)
    implementation(projects.impl.todoCart)
    implementation(projects.impl.sessionCheckout)
    implementation(projects.impl.cartUser)
    implementation(projects.impl.photoCart)
    implementation(projects.impl.identityCheckout)
    implementation(projects.impl.profileUser)
    implementation(projects.impl.checkoutUser)
    implementation(projects.impl.alarmCheckout)
    implementation(projects.impl.networkCart)
    implementation(projects.impl.videoIdentity)
    implementation(projects.impl.documentCart)
    implementation(projects.impl.sessionCart)
    implementation(projects.impl.shareCart)
    implementation(projects.impl.reportCheckout)
    implementation(projects.impl.contactUser)
    implementation(projects.impl.networkCheckout)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}