plugins {
    id("awesome-android-lib")
}

dependencies {
    implementation(projects.impl.checkoutCheckout)
    implementation(projects.impl.feedCheckout)
    implementation(projects.impl.accountCheckout)
    implementation(projects.impl.statusCheckout)
    implementation(projects.impl.locationCart)
    implementation(projects.impl.photoCheckout)
    implementation(projects.impl.searchCheckout)
    implementation(projects.impl.checkoutCart)
    implementation(projects.impl.analyticsCart)
    implementation(projects.impl.notificationCart)
    implementation(projects.impl.listCheckout)
    implementation(projects.impl.fileCart)
    implementation(projects.impl.sessionCart)
    implementation(projects.impl.profileCheckout)
    implementation(projects.impl.accountCart)
    implementation(projects.impl.videoCart)
    implementation(projects.impl.postCart)
    implementation(projects.impl.identityCheckout)
    implementation(projects.impl.taskCart)
    implementation(projects.impl.locationUser)
    implementation(projects.impl.podcastIdentity)
    implementation(projects.impl.searchCart)
    implementation(projects.impl.searchUser)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}