plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":impl:identity-cart"))
    implementation(project(":impl:share-cart"))
    implementation(project(":impl:podcast-cart"))
    implementation(project(":impl:group-checkout"))
    implementation(project(":impl:contact-cart"))
    implementation(project(":impl:status-cart"))
    implementation(project(":impl:metric-checkout"))
    implementation(project(":impl:login-checkout"))
    implementation(project(":impl:calendar-cart"))
    implementation(project(":impl:login-user"))
    implementation(project(":impl:push-user"))
    implementation(project(":impl:notification-checkout"))
    implementation(project(":impl:video-cart"))
    implementation(project(":impl:alarm-cart"))
    implementation(project(":impl:account-checkout"))
    implementation(project(":impl:article-identity"))
    implementation(project(":impl:message-user"))
    implementation(project(":impl:video-identity"))
    implementation(project(":impl:audio-cart"))
    implementation(project(":impl:share-checkout"))
    implementation(project(":impl:identity-user"))
    implementation(project(":impl:photo-identity"))
    implementation(project(":impl:photo-checkout"))
    implementation(project(":impl:timer-cart"))
    implementation(project(":impl:status-checkout"))
    implementation(project(":impl:message-checkout"))
    implementation(project(":impl:article-checkout"))
    implementation(project(":impl:playlist-identity"))
    implementation(project(":impl:login-cart"))
    implementation(project(":impl:user-checkout"))
    implementation(project(":impl:map-checkout"))
    implementation(project(":impl:contact-checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}