plugins {
    id("awesome-android-lib")
}

dependencies {
    implementation(projects.impl.userCart)
    implementation(projects.impl.userCheckout)
    implementation(projects.impl.galleryCheckout)
    implementation(projects.impl.messageUser)
    implementation(projects.impl.groupUser)
    implementation(projects.impl.contactUser)
    implementation(projects.impl.groupCart)
    implementation(projects.impl.articleIdentity)
    implementation(projects.impl.accountCart)
    implementation(projects.impl.profileCart)
    implementation(projects.impl.shareCheckout)
    implementation(projects.impl.reportCart)
    implementation(projects.impl.profileUser)
    implementation(projects.impl.todoCheckout)
    implementation(projects.impl.timerCheckout)
    implementation(projects.impl.notificationCheckout)
    implementation(projects.impl.calendarCheckout)
    implementation(projects.impl.playlistIdentity)
    implementation(projects.impl.searchUser)
    implementation(projects.impl.syncCheckout)
    implementation(projects.impl.taskCart)
    implementation(projects.impl.mapCart)
    implementation(projects.impl.loginUser)
    implementation(projects.impl.galleryIdentity)
    implementation(projects.impl.userUser)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}