rootProject.name = "androidRhombus100modules"

pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":core:push")
include(":core:contact")
include(":core:login")
include(":core:identity")
include(":feature:checkout")
include(":feature:cart")
include(":feature:user")
include(":feature:profile")
include(":feature:feed")
include(":feature:comment")
include(":domain:post")
include(":domain:search")
include(":domain:location")
include(":domain:network")
include(":domain:sync")
include(":domain:share")
include(":domain:groups")
include(":domain:message")
include(":domain:notification")
include(":repository:setting")
include(":repository:account")
include(":repository:session")
include(":repository:analytics")
include(":repository:report")
include(":repository:log")
include(":repository:status")
include(":repository:metric")
include(":repository:task")
include(":repository:calendar")
include(":repository:event")
include(":repository:alarm")
include(":repository:timer")
include(":repository:file")
include(":repository:document")
include(":repository:note")
include(":repository:todo")
include(":repository:list")
include(":model:map")
include(":model:weather")
include(":model:forecast")
include(":model:news")
include(":model:article")
include(":model:podcast")
include(":model:video")
include(":model:photo")
include(":model:gallery")
include(":model:media")
include(":model:audio")
include(":model:playlist")
include(":model:push-contact")
include(":model:contact-contact")
include(":model:login-contact")
include(":model:identity-contact")
include(":model:checkout-contact")
include(":model:cart-contact")
include(":model:user-contact")
include(":model:profile-contact")
include(":model:feed-contact")
include(":model:comment-contact")
include(":model:post-contact")
include(":model:search-contact")
include(":model:location-contact")
include(":entity:network-contact")
include(":entity:sync-contact")
include(":entity:share-contact")
include(":entity:group-contact")
include(":entity:message-contact")
include(":entity:notification-contact")
include(":entity:setting-contact")
include(":entity:account-contact")
include(":entity:session-contact")
include(":entity:analytics-contact")
include(":entity:report-contact")
include(":entity:log-contact")
include(":entity:status-contact")
include(":entity:metric-contact")
include(":entity:task-contact")
include(":entity:calendar-contact")
include(":entity:event-contact")
include(":data:alarm-contact")
include(":data:timer-contact")
include(":data:file-contact")
include(":data:document-contact")
include(":data:note-contact")
include(":data:todo-contact")
include(":data:list-contact")
include(":data:map-contact")
include(":api:weather-contact")
include(":api:forecast-contact")
include(":api:news-contact")
include(":api:article-contact")
include(":api:podcast-contact")
include(":presentation:video-contact")
include(":presentation:photo-contact")
include(":presentation:gallery-contact")
include(":presentation:media-contact")
include(":ui:audio-contact")
include(":ui:playlist-contact")
include(":ui:push-login")
include(":app:app")
