plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":impl:weather-checkout"))
    implementation(project(":impl:identity-checkout"))
    implementation(project(":impl:analytics-cart"))
    implementation(project(":impl:gallery-identity"))
    implementation(project(":impl:playlist-checkout"))
    implementation(project(":impl:audio-cart"))
    implementation(project(":impl:comment-cart"))
    implementation(project(":impl:login-cart"))
    implementation(project(":impl:map-checkout"))
    implementation(project(":impl:location-checkout"))
    implementation(project(":impl:post-cart"))
    implementation(project(":impl:event-checkout"))
    implementation(project(":impl:document-checkout"))
    implementation(project(":impl:network-user"))
    implementation(project(":impl:media-cart"))
    implementation(project(":impl:article-cart"))
    implementation(project(":impl:list-checkout"))
    implementation(project(":impl:video-checkout"))
    implementation(project(":impl:news-cart"))
    implementation(project(":impl:setting-checkout"))
    implementation(project(":impl:identity-user"))
    implementation(project(":impl:todo-checkout"))
    implementation(project(":impl:checkout-user"))
    implementation(project(":impl:playlist-identity"))
    implementation(project(":impl:forecast-checkout"))
    implementation(project(":impl:file-cart"))
    implementation(project(":impl:article-checkout"))
    implementation(project(":impl:timer-checkout"))
    implementation(project(":impl:search-cart"))
    implementation(project(":impl:calendar-checkout"))
    implementation(project(":impl:cart-checkout"))
    implementation(project(":impl:post-user"))
    implementation(project(":impl:file-checkout"))
    implementation(project(":impl:todo-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}