plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":service:audio-login"))
    implementation(project(":service:file-login"))
    implementation(project(":service:report-identity"))
    implementation(project(":service:metric-identity"))
    implementation(project(":service:list-login"))
    implementation(project(":service:push-identity"))
    implementation(project(":service:post-identity"))
    implementation(project(":service:map-identity"))
    implementation(project(":service:setting-identity"))
    implementation(project(":service:timer-identity"))
    implementation(project(":service:account-identity"))
    implementation(project(":service:todo-login"))
    implementation(project(":service:notification-identity"))
    implementation(project(":service:weather-login"))
    implementation(project(":service:task-identity"))
    implementation(project(":service:video-login"))
    implementation(project(":service:cart-identity"))
    implementation(project(":service:share-identity"))
    implementation(project(":service:media-login"))
    implementation(project(":service:forecast-identity"))
    implementation(project(":service:contact-identity"))
    implementation(project(":service:document-login"))
    implementation(project(":service:gallery-login"))
    implementation(project(":service:calendar-identity"))
    implementation(project(":service:timer-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}