import org.example.awesome.AwesomeToolchains
import org.example.awesome.AwesomeProjectUtils
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension

plugins {
    id("com.android.application")
    id("com.google.devtools.ksp")
    id("dagger.hilt.android.plugin")
    id("org.jetbrains.kotlin.plugin.compose")
}

extensions.getByType(com.android.build.api.dsl.ApplicationExtension).with {
    namespace = "com.awesome." + AwesomeProjectUtils.asProjectNameToNamespace(project.name)
    compileSdk = 37
    defaultConfig {
        applicationId = "com.awesome." + AwesomeProjectUtils.asProjectNameToNamespace(project.name)
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        getByName("release") {
            minifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    buildFeatures {
        compose = true
    }
}

extensions.getByType(KotlinAndroidProjectExtension).with {
    jvmToolchain(AwesomeToolchains.javaToolchainVersion)
}

extensions.getByType(JavaPluginExtension).with {
    toolchain.languageVersion.set(JavaLanguageVersion.of(AwesomeToolchains.javaToolchainVersion))
}

// Hilt missing Java Toolchain support https://github.com/google/dagger/issues/4623
def toolchains = extensions.getByType(JavaToolchainService)
tasks.withType(JavaCompile)
    .matching { it.name.startsWith("hiltJavaCompile") }
    .configureEach {
        javaCompiler.set(
            toolchains.compilerFor {
                languageVersion.set(JavaLanguageVersion.of(AwesomeToolchains.javaToolchainVersion))
            }
        )
    }
