plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":plugin:message-profile"))
    implementation(project(":plugin:list-user"))
    implementation(project(":plugin:identity-profile"))
    implementation(project(":plugin:media-user"))
    implementation(project(":plugin:account-user"))
    implementation(project(":plugin:log-user"))
    implementation(project(":plugin:report-user"))
    implementation(project(":plugin:event-user"))
    implementation(project(":plugin:comment-profile"))
    implementation(project(":plugin:notification-user"))
    implementation(project(":plugin:report-profile"))
    implementation(project(":plugin:profile-profile"))
    implementation(project(":plugin:event-profile"))
    implementation(project(":plugin:calendar-user"))
    implementation(project(":plugin:weather-user"))
    implementation(project(":plugin:contact-profile"))
    implementation(project(":plugin:article-user"))
    implementation(project(":plugin:analytics-user"))
    implementation(project(":plugin:task-user"))
    implementation(project(":plugin:checkout-profile"))
    implementation(project(":plugin:status-user"))
    implementation(project(":plugin:map-user"))
    implementation(project(":plugin:playlist-user"))
    implementation(project(":plugin:sync-profile"))
    implementation(project(":plugin:calendar-profile"))
    implementation(project(":plugin:audio-user"))
    implementation(project(":plugin:task-profile"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}