plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(projects.plugin.searchProfile)
    implementation(projects.plugin.logProfile)
    implementation(projects.plugin.commentProfile)
    implementation(projects.plugin.logUser)
    implementation(projects.plugin.analyticsProfile)
    implementation(projects.plugin.listUser)
    implementation(projects.plugin.playlistUser)
    implementation(projects.plugin.locationProfile)
    implementation(projects.plugin.checkoutProfile)
    implementation(projects.plugin.postProfile)
    implementation(projects.plugin.videoUser)
    implementation(projects.plugin.messageProfile)
    implementation(projects.plugin.reportUser)
    implementation(projects.plugin.noteUser)
    implementation(projects.plugin.metricUser)
    implementation(projects.plugin.settingProfile)
    implementation(projects.plugin.shareProfile)
    implementation(projects.plugin.identityProfile)
    implementation(projects.plugin.userProfile)
    implementation(projects.plugin.syncProfile)
    implementation(projects.plugin.mapUser)
    implementation(projects.plugin.loginProfile)
    implementation(projects.plugin.accountProfile)
    implementation(projects.plugin.mediaUser)
    implementation(projects.plugin.todoUser)
    implementation(projects.plugin.forecastUser)
    implementation(projects.plugin.statusUser)
    implementation(projects.plugin.statusProfile)
    implementation(projects.plugin.cartProfile)
    implementation(projects.plugin.profileProfile)
    implementation(projects.plugin.sessionProfile)
    implementation(projects.plugin.feedProfile)
    implementation(projects.plugin.settingUser)
    implementation(projects.plugin.galleryUser)
    implementation(projects.plugin.taskProfile)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}