plugins {
    id("awesome-android-lib")
}

dependencies {
    implementation(projects.remote.newsProfile)
    implementation(projects.remote.commentFeed)
    implementation(projects.remote.listProfile)
    implementation(projects.remote.searchFeed)
    implementation(projects.remote.alarmProfile)
    implementation(projects.remote.identityFeed)
    implementation(projects.remote.mapProfile)
    implementation(projects.remote.loginFeed)
    implementation(projects.remote.userFeed)
    implementation(projects.remote.articleProfile)
    implementation(projects.remote.fileProfile)
    implementation(projects.remote.podcastProfile)
    implementation(projects.remote.profileFeed)
    implementation(projects.remote.photoProfile)
    implementation(projects.remote.documentProfile)
    implementation(projects.remote.contactFeed)
    implementation(projects.remote.todoProfile)
    implementation(projects.remote.weatherProfile)
    implementation(projects.remote.mediaProfile)
    implementation(projects.remote.timerProfile)
    implementation(projects.remote.audioProfile)
    implementation(projects.remote.forecastProfile)
    implementation(projects.remote.playlistProfile)
    implementation(projects.remote.checkoutFeed)
    implementation(projects.remote.pushFeed)
    implementation(projects.remote.videoProfile)
    implementation(projects.remote.postFeed)
    implementation(projects.remote.noteProfile)
    implementation(projects.remote.cartFeed)
    implementation(projects.remote.galleryProfile)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}