plugins {
    id("awesome-android-lib")
}

dependencies {
    implementation(projects.service.audioLogin)
    implementation(projects.service.fileLogin)
    implementation(projects.service.reportIdentity)
    implementation(projects.service.metricIdentity)
    implementation(projects.service.listLogin)
    implementation(projects.service.pushIdentity)
    implementation(projects.service.postIdentity)
    implementation(projects.service.mapIdentity)
    implementation(projects.service.settingIdentity)
    implementation(projects.service.timerIdentity)
    implementation(projects.service.accountIdentity)
    implementation(projects.service.todoLogin)
    implementation(projects.service.notificationIdentity)
    implementation(projects.service.weatherLogin)
    implementation(projects.service.taskIdentity)
    implementation(projects.service.videoLogin)
    implementation(projects.service.cartIdentity)
    implementation(projects.service.shareIdentity)
    implementation(projects.service.mediaLogin)
    implementation(projects.service.forecastIdentity)
    implementation(projects.service.contactIdentity)
    implementation(projects.service.documentLogin)
    implementation(projects.service.galleryLogin)
    implementation(projects.service.calendarIdentity)
    implementation(projects.service.timerLogin)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}