plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":impl:report-cart"))
    implementation(project(":impl:calendar-checkout"))
    implementation(project(":impl:analytics-cart"))
    implementation(project(":impl:profile-cart"))
    implementation(project(":impl:news-cart"))
    implementation(project(":impl:contact-user"))
    implementation(project(":impl:search-user"))
    implementation(project(":impl:message-cart"))
    implementation(project(":impl:alarm-cart"))
    implementation(project(":impl:timer-cart"))
    implementation(project(":impl:alarm-checkout"))
    implementation(project(":impl:gallery-cart"))
    implementation(project(":impl:contact-checkout"))
    implementation(project(":impl:podcast-cart"))
    implementation(project(":impl:list-checkout"))
    implementation(project(":impl:session-cart"))
    implementation(project(":impl:gallery-checkout"))
    implementation(project(":impl:log-cart"))
    implementation(project(":impl:list-cart"))
    implementation(project(":impl:profile-checkout"))
    implementation(project(":impl:identity-user"))
    implementation(project(":impl:feed-user"))
    implementation(project(":impl:media-cart"))
    implementation(project(":impl:share-checkout"))
    implementation(project(":impl:forecast-cart"))
    implementation(project(":impl:metric-checkout"))
    implementation(project(":impl:user-user"))
    implementation(project(":impl:log-checkout"))
    implementation(project(":impl:article-cart"))
    implementation(project(":impl:forecast-checkout"))
    implementation(project(":impl:session-checkout"))
    implementation(project(":impl:article-checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}