plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(projects.impl.reportCart)
    implementation(projects.impl.calendarCheckout)
    implementation(projects.impl.analyticsCart)
    implementation(projects.impl.profileCart)
    implementation(projects.impl.newsCart)
    implementation(projects.impl.contactUser)
    implementation(projects.impl.searchUser)
    implementation(projects.impl.messageCart)
    implementation(projects.impl.alarmCart)
    implementation(projects.impl.timerCart)
    implementation(projects.impl.alarmCheckout)
    implementation(projects.impl.galleryCart)
    implementation(projects.impl.contactCheckout)
    implementation(projects.impl.podcastCart)
    implementation(projects.impl.listCheckout)
    implementation(projects.impl.sessionCart)
    implementation(projects.impl.galleryCheckout)
    implementation(projects.impl.logCart)
    implementation(projects.impl.listCart)
    implementation(projects.impl.profileCheckout)
    implementation(projects.impl.identityUser)
    implementation(projects.impl.feedUser)
    implementation(projects.impl.mediaCart)
    implementation(projects.impl.shareCheckout)
    implementation(projects.impl.forecastCart)
    implementation(projects.impl.metricCheckout)
    implementation(projects.impl.userUser)
    implementation(projects.impl.logCheckout)
    implementation(projects.impl.articleCart)
    implementation(projects.impl.forecastCheckout)
    implementation(projects.impl.sessionCheckout)
    implementation(projects.impl.articleCheckout)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}