plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(projects.impl.galleryIdentity)
    implementation(projects.impl.feedCheckout)
    implementation(projects.impl.logCheckout)
    implementation(projects.impl.analyticsCart)
    implementation(projects.impl.timerCart)
    implementation(projects.impl.articleCart)
    implementation(projects.impl.alarmCheckout)
    implementation(projects.impl.settingCart)
    implementation(projects.impl.mapCheckout)
    implementation(projects.impl.commentCart)
    implementation(projects.impl.playlistIdentity)
    implementation(projects.impl.checkoutCart)
    implementation(projects.impl.identityCheckout)
    implementation(projects.impl.sessionCart)
    implementation(projects.impl.mediaCheckout)
    implementation(projects.impl.networkUser)
    implementation(projects.impl.galleryCheckout)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}