plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":model:user-contact"))
    implementation(project(":model:podcast"))
    implementation(project(":model:article"))
    implementation(project(":model:video"))
    implementation(project(":model:news"))
    implementation(project(":model:identity-contact"))
    implementation(project(":model:search-contact"))
    implementation(project(":model:profile-contact"))
    implementation(project(":model:post-contact"))
    implementation(project(":model:checkout-contact"))
    implementation(project(":model:forecast"))
    implementation(project(":model:push-contact"))
    implementation(project(":model:audio"))
    implementation(project(":model:comment-contact"))
    implementation(project(":model:login-contact"))
    implementation(project(":model:media"))
    implementation(project(":model:weather"))
    implementation(project(":model:playlist"))
    implementation(project(":model:contact-contact"))
    implementation(project(":model:feed-contact"))
    implementation(project(":model:map"))
    implementation(project(":model:gallery"))
    implementation(project(":model:location-contact"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    ksp(libs.kotlin.jvm.metadata)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}