plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":impl:article-cart"))
    implementation(project(":impl:group-cart"))
    implementation(project(":impl:share-cart"))
    implementation(project(":impl:profile-cart"))
    implementation(project(":impl:log-checkout"))
    implementation(project(":impl:cart-cart"))
    implementation(project(":impl:forecast-cart"))
    implementation(project(":impl:article-checkout"))
    implementation(project(":impl:analytics-cart"))
    implementation(project(":impl:checkout-checkout"))
    implementation(project(":impl:contact-user"))
    implementation(project(":impl:playlist-identity"))
    implementation(project(":impl:location-checkout"))
    implementation(project(":impl:feed-checkout"))
    implementation(project(":impl:sync-cart"))
    implementation(project(":impl:profile-checkout"))
    implementation(project(":impl:post-user"))
    implementation(project(":impl:push-checkout"))
    implementation(project(":impl:profile-user"))
    implementation(project(":impl:weather-checkout"))
    implementation(project(":impl:metric-cart"))
    implementation(project(":impl:comment-cart"))
    implementation(project(":impl:document-cart"))
    implementation(project(":impl:article-identity"))
    implementation(project(":impl:comment-checkout"))
    implementation(project(":impl:calendar-checkout"))
    implementation(project(":impl:account-cart"))
    implementation(project(":impl:podcast-identity"))
    implementation(project(":impl:news-identity"))
    implementation(project(":impl:notification-cart"))
    implementation(project(":impl:checkout-user"))
    implementation(project(":impl:identity-checkout"))
    implementation(project(":impl:sync-checkout"))
    implementation(project(":impl:playlist-checkout"))
    implementation(project(":impl:post-cart"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}