plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":remote:gallery-profile"))
    implementation(project(":remote:profile-feed"))
    implementation(project(":remote:file-profile"))
    implementation(project(":remote:user-feed"))
    implementation(project(":remote:list-profile"))
    implementation(project(":remote:article-profile"))
    implementation(project(":remote:push-feed"))
    implementation(project(":remote:audio-profile"))
    implementation(project(":remote:search-feed"))
    implementation(project(":remote:checkout-feed"))
    implementation(project(":remote:alarm-profile"))
    implementation(project(":remote:podcast-profile"))
    implementation(project(":remote:feed-feed"))
    implementation(project(":remote:map-profile"))
    implementation(project(":remote:contact-feed"))
    implementation(project(":remote:todo-profile"))
    implementation(project(":remote:cart-feed"))
    implementation(project(":remote:comment-feed"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}