plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(projects.service.feedIdentity)
    implementation(projects.service.fileIdentity)
    implementation(projects.service.todoLogin)
    implementation(projects.service.listIdentity)
    implementation(projects.service.noteLogin)
    implementation(projects.service.weatherIdentity)
    implementation(projects.service.audioLogin)
    implementation(projects.service.forecastLogin)
    implementation(projects.service.sessionIdentity)
    implementation(projects.service.accountIdentity)
    implementation(projects.service.commentIdentity)
    implementation(projects.service.checkoutIdentity)
    implementation(projects.service.reportIdentity)
    implementation(projects.service.cartIdentity)
    implementation(projects.service.messageIdentity)
    implementation(projects.service.timerLogin)
    implementation(projects.service.eventIdentity)
    implementation(projects.service.eventLogin)
    implementation(projects.service.analyticsIdentity)
    implementation(projects.service.pushIdentity)
    implementation(projects.service.metricIdentity)
    implementation(projects.service.userIdentity)
    implementation(projects.service.calendarLogin)
    implementation(projects.service.shareIdentity)
    implementation(projects.service.newsLogin)
    implementation(projects.service.settingIdentity)
    implementation(projects.service.mediaLogin)
    implementation(projects.service.podcastLogin)
    implementation(projects.service.calendarIdentity)
    implementation(projects.service.profileIdentity)
    implementation(projects.service.documentLogin)
    implementation(projects.service.weatherLogin)
    implementation(projects.service.loginIdentity)
    implementation(projects.service.logIdentity)
    implementation(projects.service.forecastIdentity)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}