plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(projects.infra.analyticsLogin)
    implementation(projects.infra.commentLogin)
    implementation(projects.infra.contactLogin)
    implementation(projects.infra.settingLogin)
    implementation(projects.infra.sessionLogin)
    implementation(projects.infra.metricLogin)
    implementation(projects.infra.reportLogin)
    implementation(projects.infra.accountLogin)
    implementation(projects.infra.checkoutLogin)
    implementation(projects.infra.playlistContact)
    implementation(projects.infra.audioContact)
    implementation(projects.infra.locationLogin)
    implementation(projects.infra.pushLogin)
    implementation(projects.infra.groupLogin)
    implementation(projects.infra.searchLogin)
    implementation(projects.infra.shareLogin)
    implementation(projects.infra.userLogin)
    implementation(projects.infra.feedLogin)
    implementation(projects.infra.mediaContact)
    implementation(projects.infra.loginLogin)
    implementation(projects.infra.networkLogin)
    implementation(projects.infra.profileLogin)
    implementation(projects.infra.taskLogin)
    implementation(projects.infra.notificationLogin)
    implementation(projects.infra.statusLogin)
    implementation(projects.infra.syncLogin)
    implementation(projects.infra.logLogin)
    implementation(projects.infra.postLogin)
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}